### ISSUE TITLE
Npm package is not available

### ISSUE THREAD

**Issue by jmcstreet** [ADAO-Summon/useCardanoWeb3Auth#2]
Hello team!

Could you please point us to the right npm package? The path provided does not seem to work and that npm package could be found manually either. Thanks!

**Comment by rodrigomd94** [comment]
> Hello team!
> 
> Could you please point us to the right npm package? The path provided does not seem to work and that npm package could be found manually either. Thanks!

Hey. Sorry it was not published to npm yet but you should be able to install it now.

https://www.npmjs.com/package/use-cardano-web3-auth
