### ISSUE TITLE
Google cloud OAuth 2.0 Client IDs

### ISSUE THREAD

**Issue by Alexnorvag** [ADAO-Summon/useCardanoWeb3Auth#3]
### I have a problem with creating a web 3 wallet. 

I use the code from the example, but when I replace your clientId with my own, the wallet stops being created and I don't see **cardanoAddress** and **cardanoWalletAPI** (it works fine with your clientId). I think I'm creating credentials incorrectly in the google console. Could you point out the features that need to be taken into account when creating, or maybe you could write a short guide on how to create credentials and clientId correctly so that clientId works properly in a web3auth application?

**Comment by rodrigomd94** [comment]
Hmm hard to say what the issue is without knowing the exact error that you are getting. The web3auth client ID is not the only thing to configure, you also need to create your verifiers on web3auth.io.

p.s.: weird that it worked with that clientID because it was just a test one that I disabled.

**Comment by Alexnorvag** [comment]
@rodrigomd94, thank you for reply. 
Unfortunately, it doesn't give me any errors. However, the wallet is not created even after successfully logging in using Google.

I have the following part of the code:

```javascript
...
const { web3Auth } = useWeb3Auth();

console.log('web3Auth -> cardanoWalletAPI: ', web3Auth?.cardanoWalletAPI);

const signWithGoogle = () => {
    web3Auth?.login('google);
}

return (
    <div onClick={signWithGoogle}>Google</div>
)
...
```

And I expect that with my `сlientId` and after executing the `signWithGoogle` function, I will see `cardanoWalletAPI` other than `null`. Currently, I have set up an account in web3auth.io, and credentials in the google cloud console. The only problem is that with your `clientId` inserted into my `web3auth` verifier, the wallet is created after calling the `signWithGoogle` function, but not with my personal `clientId`. And so I was wondering how you set up credentials in the Google cloud console.

**Comment by rodrigomd94** [comment]
> And I expect that with my `сlientId` and after executing the `selectSocial` function, I will see `cardanoWalletAPI` other than `null`. Currently, I have set up an account in web3auth.io, and credentials in the google cloud console. The only problem is that with your `clientId` inserted into my `web3auth` verifier, the wallet is created after calling the `signWithGoogle` function, but not with my personal `clientId`. And so I was wondering how you set up credentials in the Google cloud console.

I'm not sure what your `selectSocial` function does.
Did you change the verifier name to your own verifier created with web3auth? It has to be your verifier name, your web3auth client id and your google client id. If you have a repo with your code I can take a look.

**Comment by Alexnorvag** [comment]
@rodrigomd94, it seems that the problem is related to the region of the Google account. Sorry to disturb.
